/**
 * Scriptik — picks the site language from the browser
 * (navigator.languages), then keeps a manual override in storage.
 * Storage goes through safeStorage() because third-party iframes may block localStorage.
 */

import { safeStorage } from "./embed.js";
import { glueHangingPrepositions } from "./hanging-prepositions.js";

export const SUPPORTED = ["en", "ru"];
export const DEFAULT_LOCALE = "en";
export const STORAGE_KEY = "kaik-course-locale";
const storage = safeStorage();

/** English waitlist form; Russian still goes to Tribute payment. */
export const ENROLL_HREF = {
  en: "https://docs.google.com/forms/d/e/1FAIpQLSfghzk5zivpA0fB3yL9lNfX7ONCcNE612S6hqAQzx4amfG9dQ/viewform",
  ru: "https://web.tribute.tg/p/AOo",
};

function enrollHref(locale) {
  return ENROLL_HREF[locale] || ENROLL_HREF[DEFAULT_LOCALE];
}

const dictionaries = {
  en: {
    title: "ETTER II",
    dates: "from 14 september\nto 26 october",
    "dates.short": "14 september – 26 october",
    "dates.stack": "14 september\n26 october",
    "landing.title": "LETTER II",
    "landing.dates": "from 14 september\nto 26 october",
    "nav.program": "program",
    "nav.work": "student work",
    "nav.catalog": "catalog",
    "nav.enroll": "join waitlist",
    "lang.label": "Language",
    "stage.settings": "settings",
    "stage.title": "position",
    "stage.lift": "all Y",
    "stage.axisX": "X",
    "stage.axisY": "Y",
    "stage.group.all": "stage",
    "stage.group.footer": "footer",
    "stage.footerY": "Y",
    "stage.group.lockup": "title",
    "stage.group.text": "text",
    "stage.textPos": "text position",
    "stage.lockupScale": "scale",
    "stage.group.nav": "nav",
    "stage.group.lang": "lang",
    "stage.group.deck": "stack",
    "stage.group.focus": "focus card",
    "stage.group.close": "close",
    "stage.group.cards": "cards",
    "stage.cardScale": "card scale",
    "stage.cardY": "card Y",
    "stage.focusScale": "scale",
    "stage.reset": "reset",
    "stage.copyJson": "copy JSON",
    "stage.copied": "copied",
    "admin.brand": "drop caps",
    "admin.site": "site",
    "admin.dropTitle": "drop SVGs here",
    "admin.dropHint": "a letter or a whole lettering — then mark type, author and tags",
    "admin.inbox": "to upload",
    "admin.author": "author",
    "admin.stream": "stream",
    "admin.applyAll": "apply to all",
    "admin.clear": "clear",
    "admin.save": "save to catalog",
    "admin.catalog": "catalog",
    "admin.letter": "letter",
    "admin.preview": "as a drop cap in a word",
    "admin.delete": "delete",
    "admin.close": "close",
    "admin.error": "Request failed",
    "admin.remove": "remove",
    "admin.count": "{n} letters",
    "admin.empty": "no letters yet — drop SVGs above",
    "admin.usage": "Select vectors, then tap construction and style. Letters become drop caps; everything shows in the catalog.",
    "admin.wordRest": "etter",
    "admin.needSvg": "drop an SVG first",
    "admin.badSvg": "not a valid SVG",
    "admin.devOnly": "saving works in local admin (npm run dev)",
    "admin.fillAll": "fill letter, author and stream",
    "admin.fillWord": "fill the word, author and stream",
    "admin.saved": "saved",
    "admin.writable": "local catalog",
    "admin.readOnly": "read only",
    "admin.confirmDelete": "Delete this work?",
    "admin.kind": "type",
    "admin.kind.letter": "letter",
    "admin.kind.word": "word",
    "admin.text": "word",
    "admin.construction": "construction",
    "admin.family": "style",
    "admin.countWords": "{n} words",
    "admin.emptyWords": "no words yet — drop SVGs above",
    "admin.openCatalog": "catalog",
    "admin.replaceFile": "replace file",
    "admin.replaceHint": "drop a new SVG or click to pick",
    "admin.replaced": "replaced",
    "admin.prev": "previous",
    "admin.next": "next",
    "sound.settings": "sound",
    "sound.title": "sounds",
    "sound.close": "close",
    "sound.volume": "volume",
    "sound.scroll.hint": "scroll sound — tap to preview and select",
    "sound.scroll.px": "px per sound",
    "sound.group.wiki": "wiki",
    "sound.group.deslop": "deslop",
    "sound.group.soundcn": "soundcn",
    "sound.group.snd": "snd",
    "sound.wiki.pop": "pop",
    "sound.wiki.tick": "tick",
    "sound.wiki.click": "click",
    "sound.wiki.whoosh": "whoosh",
    "sound.wiki.toggle": "toggle",
    "sound.wiki.success": "success",
    "sound.wiki.confirm": "confirm",
    "sound.wiki.error": "error",
    "sound.wiki.warning": "warning",
    "sound.deslop.tick": "tick",
    "sound.deslop.press": "press",
    "sound.deslop.click": "click",
    "catalog.brand": "catalog",
    "catalog.letters": "letters",
    "catalog.words": "words",
    "catalog.all": "all",
    "catalog.emptyLetters": "no letters yet",
    "catalog.emptyWords": "no words yet",
    "catalog.site": "course",
    "catalog.close": "close",
    "tax.construction.modular": "modular",
    "tax.construction.stylized": "stylized",
    "tax.construction.experimental": "experimental",
    "tax.family.gothic": "gothic",
    "tax.family.antiqua": "antiqua",
    "tax.family.grotesque": "grotesque",
    "tax.family.script": "script",
    "tax.family.display": "display",
    "fold.open": "Open the letter",
    "fold.close": "Close the letter",
    "fold.body": "the top stays facing you. this is the first stretch of a long sheet — too long for the card, so it arrived folded.",
    "fold.flap": "the first bend was toward us. open, it lies flat again and the letter can be read as one strip.",
    "fold.flap2": "then another fold. click the dim area around the letter to pack it back onto the card. if the sheet is longer than the frame, scroll it.",
    "format.weeks": "weeks",
    "format.workshops": "online workshops",
    "format.workshops.note": "we talk on Mondays and Thursdays in Zoom and draw together",
    "format.videos": "recorded videos",
    "format.videos.note": "about history, materials, typography, and so on",
    "format.sound.on": "Sound on",
    "format.sound.off": "Sound off",
    "author.title": "course author",
    "author.name": "anok regular",
    "author.open": "anok regular — open profile",
    "author.work.open": "Open lettering work",
    "author.lb.label": "Author works",
    "author.lb.close": "Close gallery",
    "author.lb.prev": "Previous work",
    "author.lb.next": "Next work",
    "program.title": "program",
    "program.open": "Open the program",
    "program.close": "Close the program",
    "program.w1": "1 week",
    "program.w2": "2 week",
    "program.w3": "3 week",
    "program.w4": "4 week",
    "program.w5": "5 week",
    "program.w6": "6 week",
    "program.kind.rec": "recording",
    "program.kind.call": "call",
    "program.kind.workshop": "workshop",
    "program.kind.review": "review",
    "program.date.sep17": "17 September, Thursday",
    "program.date.sep21": "21 September, Monday",
    "program.date.sep24": "24 September, Thursday",
    "program.date.sep28": "28 September, Monday",
    "program.date.oct5": "5 October, Monday",
    "program.date.oct12": "12 October, Monday",
    "program.date.oct19": "19 October, Monday",
    "program.date.oct22": "22 October, Thursday",
    "program.w1.a": "History of lettering and how it differs from calligraphy",
    "program.w1.b": "Tools and pipelines",
    "program.w1.c": "Authors, looking, references",
    "program.w1.d": "Final project topic discussion",
    "program.w2.a": "Gothic calligraphy",
    "program.w2.b": "Five starting exercises",
    "program.w2.c": "Taking lettering into digital",
    "program.w2.d": "Experimental typography: layout rules and breaking them",
    "program.w3.a": "Variable styling of a lettering",
    "program.w3.b": "Modular typography",
    "program.w3.c": "Lettering + typography, working with titles",
    "program.w4.a": "Modular typography",
    "program.w4.b": "Working with effects",
    "program.w4.c": "Neural nets for drawing / processing letters",
    "program.w5.a": "Preview consultation",
    "program.w6.a": "Final review of works",
    "program.w6.b": "What to do (with life) after the course",
    "exercises.title": "three exercises to create beautiful letters",
    "exercises.1": "Choose one letter. Come up with and draw as many variations of its shape as possible in 10 minutes, regardless of the references.",
    "exercises.2": "Find a long stick. Attach a pen to the end of it, and try to draw as many letters as possible in 10 minutes, holding the stick with your left hand.",
    "exercises.3": "Choose the inscription that you like. Anything from a word on an album cover to a street sign. Try to copy it first in a minute, then in 10, then in 30.",
    "preview.title": "recording of the final review",
    "progress.title": "student progress",
    "progress.week1": "1 week",
    "progress.week3": "3 week",
    "progress.week4": "4 week",
    "progress.yan": "yan — open Instagram",
    "progress.polina": "polina — open Instagram",
    "progress.alena": "alena — open Instagram",
    "name.alyona": "Alyona",
    "name.andrei": "Andrei",
    "name.kira": "Kira",
    "name.nadya": "Nadya",
    "name.masha": "Masha",
    "name.mashaPolina": "Masha Polina",
    "name.danil": "Danil",
    "name.polina": "Polina",
    "name.roma": "Roma",
    "name.ksusha": "Ksusha",
    "name.ksushaDash": "Ksusha —",
    "name.bogdan": "Bogdan",
    "name.alena": "Alena",
    "name.katya": "Katya",
    "name.yan": "Yan",
    "name.nadyaPlus": "nadya +",
    "name.anya": "Anya",
    "name.alyonaLc": "alyona",
    "name.progress.yan": "yan",
    "name.progress.polina": "polina",
    "name.progress.alena": "alena",
    "work.open": "Open student progress",
    "work.close": "Close student progress",
    "work.prev": "Previous student",
    "work.next": "Next student",
    "works.title": "student works",
    "works.open": "Open student works",
    "works.close": "Close student works",
    "work.week1": "1 week",
    "work.week2": "2 week",
    "work.week3": "3 week",
    "work.week4": "4 week",
    "work.week5": "5 week (not yet)",
    "work.week6": "6 week (not yet)",
    "work.final": "Final project (not yet)",
    "work.blurb": "A review will go here.",
    "faq.title": "questions and answers",
    "faq.tablet.q": "Do I need a graphics tablet?",
    "faq.tablet.a": "No, a graphics tablet is not required. But if you have one, it will be more convenient to work with.",
    "faq.need.q": "What will I need?",
    "faq.need.tools": "Adobe Illustrator, Adobe Photoshop, Figma",
    "faq.need.materials": "Materials for making letters: paper, pencils, pens, markers, etc.",
    "faq.more.q": "Still have questions?",
    "faq.more.a": "Ask them here: ",
    "card.open": "Open card",
    "card.close": "Close card",
    "illust.open": "open me",
    "illust.close": "close me",
    "history.open": "Open the lettering history",
    "history.close": "Close the lettering history",
    "history.prev": "Previous image",
    "history.next": "Next image",
    "history.kicker": "if you're still bored...",
    "history.title.1": "A Very Brief Visual",
    "history.title.2": "History of ",
    "history.title.3": "Letter(-ing).",
    "history.p1": "As a species, people need communication. People also love beautiful things. Lettering, or the Art of Drawing a Letter, emerges from combination of this two existential requirements.",
    "history.cap.mielot": "↳ The scribe Jean Mielot in the writing room (secretary of the duke), between 1450 and 1460.",
    "history.p2": "The very oldest examples of intentionally formed letters comes from the Roman Times. A lot has been lost, but the oldest remain in stone. Resistance of the material to writing tool makes for a simplification of strokes and straightening of lines.",
    "history.cap.trajan": "↳ Pedestal inscriptions on the Trajan Column in Rome, 113 AD.",
    "history.p3": "From then, Roman letters evolved into many different forms and shapes. They migrated from Italy to the North, East and West, becoming more elaborate and strikingly beautiful.",
    "history.cap.tree": "↳ “Family Tree” of the Roman inscriptions development.",
    "history.p4": "Peoples of the former Roman Empire — dwellers of the British Isles, modern-day Central Europe, France and Italy — have significantly developped art of lettering in the early Middle Ages. Most of them are found in illuminated manuscripts.",
    "history.cap.lindisfarne": "↳ Pages from Lindisfarne Gospels, Northumberland (modern UK), 715–720",
    "history.p5": "Imagination did not stop, and slowly ornamental decorations turned into full-scale paintings inside letters.",
    "history.cap.initial": "↳ Inhabited Initial E. Montecassino, Italy. 1153",
    "history.p6": "Some more whimsical examples.",
    "history.p7": "Gradually, decorative elements moved from just Capital letters to all vowels and consonants in use. The process was also driven by the invention of the printing press which made book production much faster.",
    "history.cap.gutenberg": "↳ Page from the Gutenberg Bible, 1455",
    "history.p8": "Next significant change to the Letter happened after the industrial revolution: it became irreplaceable part of advertising.",
    "history.cap.coke": "↳ Coca-Cola lettering by Frank M. Robertson",
    "history.p9": "Industrial revolution also re-sparked interest to everything floral and natural motives in visual art — people were tired of straight lines and rationality. Welcome, Art-Nouvuae!",
    "history.cap.grasset": "↳ Posters and advertising by Eugene Grasset, 1880-s",
    "history.p10": "This type of lettering was especially loved by the Jugendstihl artsits of the early XX century!",
    "history.cap.eckmann": "↳ Posters and advertising by Otto Eckmann, late 1890-s",
    "history.p11": "And some more advertisment!",
    "history.cap.bernhard": "↳ Lettering for advertising by Lucian Berhard",
    "history.p12": "If looking at letters above made you think of psychedelic rock, then you are not wrong! In the 60-s many designers drew inspiration from floral designs of Jugendstihl posters for their musical posters. The whole gang was there: Hendrix, Janis Joplin, Grateful Dead.",
    "history.p13": "The tradition continued well into the end of XX century — reimagined multiple times, of course! Expressive naturalistic details were replaced by soled shapes. Yes, like that Paul Nicholson’s logo.",
    "history.cap.hofmann": "↳ Shape from Armin Hofmann’s Graphic Design Manual.",
    "history.p14": "Art of the letter is very alive and kicking even now!",
    "history.cap.vanok.1": "↳ Works by ",
    "history.cap.vanok.2": ", author of LETTER course in käik",
    "history.p15": "If you are eager to explore art of lettering even more, here are some suggestions from käik.pictures:",
    "history.book.weinberg": "Encyclopedia of Comparative Letterforms, Norman S. Weinberg",
    "history.book.hofmann": "Graphic Design Manual, Armin Hofmann",
    "history.book.gray": "A History of Lettering, Nicolete Gray",
    "history.book.join": "And join LETTER class",
    "history.letter": "LETTER  class",
    "history.meta.length": "Length:",
    "history.meta.weeks": "6 weeks",
    "history.meta.price": "Price:",
    "history.meta.program": "Program:",
    "history.meta.click": "Click here",
    "history.meta.start": "Start:",
    "history.join": "JOIN WAITLIST",
  },
  ru: {
    title: "ETTER II",
    dates: "с 14 сентября\nпо 26 октября",
    "dates.short": "14 сентября – 26 октября",
    "dates.stack": "14 сентября\n26 октября",
    "landing.title": "LETTER II",
    "landing.dates": "с 14 сентября\nпо 26 октября",
    "nav.program": "программа",
    "nav.work": "работы студентов",
    "nav.catalog": "каталог",
    "nav.enroll": "записаться",
    "lang.label": "Язык",
    "stage.settings": "настройки",
    "stage.title": "положение",
    "stage.lift": "все Y",
    "stage.axisX": "X",
    "stage.axisY": "Y",
    "stage.group.all": "сцена",
    "stage.group.footer": "нижний блок",
    "stage.footerY": "Y",
    "stage.group.lockup": "титул",
    "stage.group.text": "текст",
    "stage.textPos": "позиция текста",
    "stage.lockupScale": "скейл",
    "stage.group.nav": "меню",
    "stage.group.lang": "язык",
    "stage.group.deck": "стопка",
    "stage.group.focus": "карточка в фокусе",
    "stage.group.close": "закрыть",
    "stage.group.cards": "карточки",
    "stage.cardScale": "скейл карточек",
    "stage.cardY": "карточки Y",
    "stage.focusScale": "скейл",
    "stage.reset": "сброс",
    "stage.copyJson": "копия JSON",
    "stage.copied": "скопировано",
    "admin.brand": "буквицы",
    "admin.site": "сайт",
    "admin.dropTitle": "перетащи SVG сюда",
    "admin.dropHint": "буква или целый леттеринг — потом тип, автор и теги",
    "admin.inbox": "к загрузке",
    "admin.author": "автор",
    "admin.stream": "поток",
    "admin.applyAll": "проставить всем",
    "admin.clear": "очистить",
    "admin.save": "сохранить в каталог",
    "admin.catalog": "каталог",
    "admin.letter": "буква",
    "admin.preview": "как буквица в слове",
    "admin.delete": "удалить",
    "admin.close": "закрыть",
    "admin.error": "Не вышло",
    "admin.remove": "убрать",
    "admin.count": "{n} букв",
    "admin.empty": "пока пусто — перетащи SVG сверху",
    "admin.usage": "Выбери векторы и ткни построение или стиль — тег встанет на всех. Буквы идут в буквицы, всё — в каталог.",
    "admin.wordRest": "еттер",
    "admin.needSvg": "сначала перетащи SVG",
    "admin.badSvg": "это не SVG",
    "admin.devOnly": "сохранение работает в локальной админке (npm run dev)",
    "admin.fillAll": "заполни букву, автора и поток",
    "admin.fillWord": "заполни слово, автора и поток",
    "admin.saved": "сохранено",
    "admin.writable": "локальный каталог",
    "admin.readOnly": "только чтение",
    "admin.confirmDelete": "Удалить эту работу?",
    "admin.kind": "тип",
    "admin.kind.letter": "буква",
    "admin.kind.word": "слово",
    "admin.text": "слово",
    "admin.construction": "построение",
    "admin.family": "стиль",
    "admin.countWords": "{n} слов",
    "admin.emptyWords": "пока нет слов — перетащи SVG сверху",
    "admin.openCatalog": "каталог",
    "admin.replaceFile": "заменить файл",
    "admin.replaceHint": "перетащи новый SVG или нажми, чтобы выбрать",
    "admin.replaced": "заменён",
    "admin.prev": "назад",
    "admin.next": "дальше",
    "sound.settings": "звук",
    "sound.title": "звуки",
    "sound.close": "закрыть",
    "sound.volume": "громкость",
    "sound.scroll.hint": "звук скролла — нажми, чтобы послушать и выбрать",
    "sound.scroll.px": "пикселей на звук",
    "sound.group.wiki": "wiki",
    "sound.group.deslop": "deslop",
    "sound.group.soundcn": "soundcn",
    "sound.group.snd": "snd",
    "sound.wiki.pop": "pop",
    "sound.wiki.tick": "tick",
    "sound.wiki.click": "click",
    "sound.wiki.whoosh": "whoosh",
    "sound.wiki.toggle": "toggle",
    "sound.wiki.success": "success",
    "sound.wiki.confirm": "confirm",
    "sound.wiki.error": "error",
    "sound.wiki.warning": "warning",
    "sound.deslop.tick": "tick",
    "sound.deslop.press": "press",
    "sound.deslop.click": "click",
    "catalog.brand": "каталог",
    "catalog.letters": "буквы",
    "catalog.words": "слова",
    "catalog.all": "все",
    "catalog.emptyLetters": "пока нет букв",
    "catalog.emptyWords": "пока нет слов",
    "catalog.site": "курс",
    "catalog.close": "закрыть",
    "tax.construction.modular": "модульная",
    "tax.construction.stylized": "стилизованная",
    "tax.construction.experimental": "экспериментальная",
    "tax.family.gothic": "готическая",
    "tax.family.antiqua": "антиква",
    "tax.family.grotesque": "гротеск",
    "tax.family.script": "скрипт",
    "tax.family.display": "акцидент",
    "fold.open": "Открыть письмо",
    "fold.close": "Закрыть письмо",
    "fold.body": "верх остаётся к тебе лицом. это первый кусок длинного листа — на карточку он не влезал, поэтому приехал сложенным.",
    "fold.flap": "первый сгиб был к нам. в открытом виде он снова плоский, и письмо читается одной полосой.",
    "fold.flap2": "потом ещё один сгиб. клик по затемнению вокруг — и лист снова сложится на карточку. если он длиннее окна, его можно скроллить.",
    "format.weeks": "недель",
    "format.workshops": "онлайн-воркшопы",
    "format.workshops.note": "говорим по понедельникам и четвергам в Zoom и рисуем вместе",
    "format.videos": "записанных видео",
    "format.videos.note": "про историю, материалы, типографику и так далее",
    "format.sound.on": "Включить звук",
    "format.sound.off": "Выключить звук",
    "author.title": "автор курса",
    "author.name": "anok regular",
    "author.open": "anok regular — открыть профиль",
    "author.work.open": "Открыть работу",
    "author.lb.label": "Работы автора",
    "author.lb.close": "Закрыть галерею",
    "author.lb.prev": "Предыдущая работа",
    "author.lb.next": "Следующая работа",
    "program.title": "программа",
    "program.open": "Открыть программу",
    "program.close": "Закрыть программу",
    "program.w1": "1 неделя",
    "program.w2": "2 неделя",
    "program.w3": "3 неделя",
    "program.w4": "4 неделя",
    "program.w5": "5 неделя",
    "program.w6": "6 неделя",
    "program.kind.rec": "запись",
    "program.kind.call": "звонок",
    "program.kind.workshop": "воркшоп",
    "program.kind.review": "просмотр",
    "program.date.sep17": "17 сентября, Четверг",
    "program.date.sep21": "21 сентября, Понедельник",
    "program.date.sep24": "24 сентября, Четверг",
    "program.date.sep28": "28 сентября, Понедельник",
    "program.date.oct5": "5 октября, Понедельник",
    "program.date.oct12": "12 октября, Понедельник",
    "program.date.oct19": "19 октября, Понедельник",
    "program.date.oct22": "22 октября, Четверг",
    "program.w1.a": "История леттеринга и отличие от каллиграфии",
    "program.w1.b": "Инструменты и пайплайны",
    "program.w1.c": "Авторы, насмотренность, референсы",
    "program.w1.d": "Обсуждение тем для финального проекта",
    "program.w2.a": "Готическая каллиграфия",
    "program.w2.b": "Пять стартовых упражнений",
    "program.w2.c": "Перевод надписи в диджитал",
    "program.w2.d": "Экспериментальная типографика: правила вёрстки и их разрушение",
    "program.w3.a": "Вариативная стилизация надписи",
    "program.w3.b": "Модульная типографика",
    "program.w3.c": "Леттеринг + типографика, работа с титрами",
    "program.w4.a": "Модульная типографика",
    "program.w4.b": "Работа с эффектами",
    "program.w4.c": "Нейросети для рисования/обработки букв",
    "program.w5.a": "Консультация-предпросмотр",
    "program.w6.a": "Финальный просмотр работ",
    "program.w6.b": "Что делать (с жизнью) после курса",
    "exercises.title": "три упражнения, чтобы создавать красивые буквы",
    "exercises.1": "Выбери одну букву. Придумай и нарисуй как можно больше вариаций её формы за 10 минут, не опираясь на референсы.",
    "exercises.2": "Найди длинную палку. Прикрепи ручку на конец и попробуй нарисовать как можно больше букв за 10 минут, держа палку левой рукой.",
    "exercises.3": "Выбери надпись, которая тебе нравится. Что угодно — от слова на обложке альбома до уличной вывески. Попробуй скопировать её сначала за минуту, потом за 10, потом за 30.",
    "preview.title": "запись финального просмотра",
    "progress.title": "прогресс студентов",
    "progress.week1": "1 неделя",
    "progress.week3": "3 неделя",
    "progress.week4": "4 неделя",
    "progress.yan": "ян — открыть Instagram",
    "progress.polina": "полина — открыть Instagram",
    "progress.alena": "алена — открыть Instagram",
    "name.alyona": "Алёна",
    "name.andrei": "Андрей",
    "name.kira": "Кира",
    "name.nadya": "Надя",
    "name.masha": "Маша",
    "name.mashaPolina": "Маша Полина",
    "name.progress.yan": "ян",
    "name.progress.polina": "полина",
    "name.progress.alena": "алена",
    "name.danil": "Данил",
    "name.polina": "Полина",
    "name.roma": "Рома",
    "name.ksusha": "Ксюша",
    "name.ksushaDash": "Ксюша —",
    "name.bogdan": "Богдан",
    "name.alena": "Алена",
    "name.katya": "Катя",
    "name.yan": "Ян",
    "name.nadyaPlus": "надя +",
    "name.anya": "Аня",
    "name.alyonaLc": "алёна",
    "work.open": "Открыть прогресс студента",
    "work.close": "Закрыть прогресс студента",
    "work.prev": "Предыдущий студент",
    "work.next": "Следующий студент",
    "works.title": "student works",
    "works.open": "Открыть студенческие работы",
    "works.close": "Закрыть студенческие работы",
    "work.week1": "1 неделя",
    "work.week2": "2 неделя",
    "work.week3": "3 неделя",
    "work.week4": "4 неделя",
    "work.week5": "5 неделя (пока нет)",
    "work.week6": "6 неделя (пока нет)",
    "work.final": "Финальный проект (пока нет)",
    "work.blurb": "Тут будет отзыв.",
    "faq.title": "вопросы и ответы",
    "faq.tablet.q": "Нужен ли графический планшет?",
    "faq.tablet.a": "Нет, графический планшет не обязателен. Но если он у вас есть, с ним будет удобнее работать.",
    "faq.need.q": "Что понадобится для работы?",
    "faq.need.tools": "Adobe Illustrator, Adobe Photoshop, Figma",
    "faq.need.materials": "Материалы для создания букв: бумага, карандаши, ручки, маркеры и т. д.",
    "faq.more.q": "Остались вопросы?",
    "faq.more.a": "Задавайте их сюда: ",
    "card.open": "Открыть карточку",
    "card.close": "Закрыть карточку",
    "illust.open": "open me",
    "illust.close": "close me",
    "history.open": "Открыть историю леттеринга",
    "history.close": "Закрыть историю леттеринга",
    "history.prev": "Предыдущее изображение",
    "history.next": "Следующее изображение",
    "history.kicker": "если тебе всё ещё скучно...",
    "history.title.1": "Очень краткая визуальная",
    "history.title.2": "история ",
    "history.title.3": "леттеринга.",
    "history.p1": "Как виду, людям нужно общение. Люди также любят красивое. Леттеринг, или искусство рисовать букву, рождается из этих двух потребностей.",
    "history.cap.mielot": "↳ Писец Жан Миело в скриптории (секретарь герцога), между 1450 и 1460.",
    "history.p2": "Самые старые намеренно выстроенные буквы — из римских времён. Многое утрачено, но древнейшее осталось в камне. Сопротивление материала инструменту упрощает штрих и выпрямляет линии.",
    "history.cap.trajan": "↳ Надписи на пьедестале колонны Траяна в Риме, 113 н. э.",
    "history.p3": "Дальше римские буквы расходились в разные формы. Они ушли из Италии на север, восток и запад — становились сложнее и поразительно красивее.",
    "history.cap.tree": "↳ «Семейное дерево» развития римских надписей.",
    "history.p4": "Народы бывшей Римской империи — обитатели Британских островов, нынешней Центральной Европы, Франции и Италии — сильно развили искусство леттеринга в раннем Средневековье. Больше всего его видно в иллюминированных рукописях.",
    "history.cap.lindisfarne": "↳ Страницы Линдисфарнского евангелия, Нортумберленд (современная Великобритания), 715–720",
    "history.p5": "Воображение не остановилось: орнамент внутри букв постепенно стал полноценной живописью.",
    "history.cap.initial": "↳ Населённый инициал E. Монтекассино, Италия. 1153",
    "history.p6": "Ещё несколько причудливых примеров.",
    "history.p7": "Постепенно декор перешёл с одних заглавных на все гласные и согласные. Этому помогло изобретение печатного станка — книги стали делать гораздо быстрее.",
    "history.cap.gutenberg": "↳ Страница Библии Гутенберга, 1455",
    "history.p8": "Следующий большой сдвиг случился после промышленной революции: буква стала незаменимой частью рекламы.",
    "history.cap.coke": "↳ Леттеринг Coca-Cola Фрэнка М. Робертсона",
    "history.p9": "Промышленная революция также вернула интерес ко всему цветочному и природному в визуальном искусстве — людям надоели прямые линии и рациональность. Добро пожаловать, ар-нуво!",
    "history.cap.grasset": "↳ Плакаты и реклама Эжена Грассе, 1880-е",
    "history.p10": "Такой леттеринг особенно любили художники югендстиля начала XX века!",
    "history.cap.eckmann": "↳ Плакаты и реклама Отто Экманна, конец 1890-х",
    "history.p11": "И ещё немного рекламы!",
    "history.cap.bernhard": "↳ Рекламный леттеринг Люциана Бернхарда",
    "history.p12": "Если буквы выше напомнили психоделический рок — вы не ошиблись! В 60-е многие дизайнеры брали цветочные мотивы югендстиля для музыкальных афиш. Вся компания была там: Хендрикс, Дженис Джоплин, Grateful Dead.",
    "history.p13": "Традиция дожила до конца XX века — конечно, много раз переосмысленная. Выразительные натуралистичные детали сменились сплошными формами. Да, как тот логотип Пола Николсона.",
    "history.cap.hofmann": "↳ Форма из Graphic Design Manual Армина Хофманна.",
    "history.p14": "Искусство буквы живо и сейчас!",
    "history.cap.vanok.1": "↳ Работы ",
    "history.cap.vanok.2": ", автора курса LETTER в käik",
    "history.p15": "Если хочется копнуть леттеринг ещё глубже, вот несколько подсказок от käik.pictures:",
    "history.book.weinberg": "Encyclopedia of Comparative Letterforms, Norman S. Weinberg",
    "history.book.hofmann": "Graphic Design Manual, Armin Hofmann",
    "history.book.gray": "A History of Lettering, Nicolete Gray",
    "history.book.join": "И запишись на LETTER class",
    "history.letter": "LETTER  class",
    "history.meta.length": "Длительность:",
    "history.meta.weeks": "6 недель",
    "history.meta.price": "Цена:",
    "history.meta.program": "Программа:",
    "history.meta.click": "Нажми сюда",
    "history.meta.start": "Старт:",
    "history.join": "В WAITLIST",
  },
};

export function normalizeLocale(value) {
  if (!value) return null;
  const base = String(value).toLowerCase().split("-")[0];
  return SUPPORTED.includes(base) ? base : null;
}

export function detectBrowserLocale() {
  const candidates = [
    ...(navigator.languages || []),
    navigator.language,
    navigator.userLanguage,
  ].filter(Boolean);

  for (const candidate of candidates) {
    const match = normalizeLocale(candidate);
    if (match) return match;
  }

  return DEFAULT_LOCALE;
}

export function getLocale() {
  const saved = normalizeLocale(storage.getItem(STORAGE_KEY));
  if (saved) return saved;

  const fromHtml = normalizeLocale(
    document.documentElement.getAttribute("data-locale") ||
      document.documentElement.lang,
  );
  if (fromHtml) return fromHtml;

  return detectBrowserLocale();
}

export function setLocale(locale) {
  const next = normalizeLocale(locale) || DEFAULT_LOCALE;
  storage.setItem(STORAGE_KEY, next);
  applyTranslations(next);
  return next;
}

export function t(key, locale = getLocale()) {
  return dictionaries[locale]?.[key] ?? dictionaries[DEFAULT_LOCALE][key] ?? key;
}

export function applyTranslations(locale = getLocale()) {
  document.documentElement.lang = locale;
  document.documentElement.setAttribute("data-locale", locale);
  document.documentElement.classList.toggle("lang-ru", locale === "ru");
  document.documentElement.classList.add("i18n-ready");

  document.querySelectorAll("[data-i18n]").forEach((node) => {
    const key = node.getAttribute("data-i18n");
    if (!key) return;
    node.textContent = t(key, locale);
    if (key === "nav.enroll" && node instanceof HTMLAnchorElement) {
      node.setAttribute("href", enrollHref(locale));
    }
  });

  document.querySelectorAll("[data-i18n-aria]").forEach((node) => {
    const key = node.getAttribute("data-i18n-aria");
    if (!key) return;
    node.setAttribute("aria-label", t(key, locale));
  });

  document.querySelectorAll("[data-lang]").forEach((btn) => {
    const active = btn.getAttribute("data-lang") === locale;
    btn.classList.toggle("is-active", active);
    btn.setAttribute("aria-pressed", active ? "true" : "false");
  });

  document.dispatchEvent(new CustomEvent("kaik:translated", { detail: { locale } }));
  glueHangingPrepositions(document.body);
}

export function boot() {
  applyTranslations(getLocale());
}
